//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
#if NET_CF20


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="cf.blobtracker.y2007.m03, version=0.0.0.0, culture=neutral, publickeytoken=d159440a8" +
    "502d2da")]

#else


[assembly: ServiceDeclaration(DssServiceDeclaration.Proxy, SourceAssemblyKey="blobtracker.y2007.m03, version=0.0.0.0, culture=neutral, publickeytoken=d159440a8" +
    "502d2da")]

#endif
[assembly: System.Security.SecurityTransparentAttribute()]
[assembly: System.Security.AllowPartiallyTrustedCallersAttribute()]
[assembly: interopservices.ComVisible(true)]


