//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using finaldemosimulator = Robotics.FinalDemoSimulator;


namespace Robotics.FinalDemoSimulator
{
    
    
    /// <summary>
    /// FinalDemoSimulator Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        public const String Identifier = "http://schemas.tempuri.org/2008/04/finaldemosimulator.html";
    }
    
    /// <summary>
    /// The FinalDemoSimulator State
    /// </summary>
    [DataContract()]
    public class FinalDemoSimulatorState
    {
    }
    
    /// <summary>
    /// FinalDemoSimulator Main Operations Port
    /// </summary>
    [ServicePort()]
    public class FinalDemoSimulatorOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get>
    {
    }
    
    /// <summary>
    /// FinalDemoSimulator Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<FinalDemoSimulatorState, Fault>>
    {
        
        /// <summary>
        /// FinalDemoSimulator Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// FinalDemoSimulator Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// FinalDemoSimulator Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<FinalDemoSimulatorState,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
