//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;


namespace Robotics.CoroBot.ImageProcessor
{
    
    
    /// <summary>
    /// ImageProcessor Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        public const String Identifier = "http://schemas.tempuri.org/2008/04/imageprocessor.html";
    }
    
    /// <summary>
    /// The ImageProcessor State
    /// </summary>
    [DataContract()]
    public class ImageProcessorState
    {
    }
    
    /// <summary>
    /// ImageProcessor Main Operations Port
    /// </summary>
    [ServicePort()]
    public class ImageProcessorOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get>
    {
    }

    [DataContract]
    public class ImageProcessorResult
    {
        public ImageProcessorResult()
        {
            folders = new List<Folder>();
        }

        private List<Folder> folders;
        [DataMember]
        public List<Folder> Folders { get { return folders; } set { folders = value; } }
    }

    [DataContract]
    public class Folder
    {
        private float x;
        private string color;
        private int area;

        [DataMember]
        public float X { get { return x; } set { x = value; } }
        [DataMember]
        public string Color { get { return color; } set { color = value; } }
        [DataMember]
        public int Area { get { return area; } set { area = value; } }
    }

    /// <summary>
    /// ImageProcessor Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ImageProcessorResult, Fault>>
    {
        
        /// <summary>
        /// ImageProcessor Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// ImageProcessor Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// ImageProcessor Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<ImageProcessorResult,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
