//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using project2 = Robotics.Project2;


namespace Robotics.Project2
{
    
    
    /// <summary>
    /// Project2 Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        public const String Identifier = "http://schemas.tempuri.org/2008/03/project2.html";
    }
    
    /// <summary>
    /// The Project2 State
    /// </summary>
    [DataContract()]
    public class Project2State
    {
    }
    
    /// <summary>
    /// Project2 Main Operations Port
    /// </summary>
    [ServicePort()]
    public class Project2Operations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get>
    {
    }
    
    /// <summary>
    /// Project2 Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<Project2State, Fault>>
    {
        
        /// <summary>
        /// Project2 Get Operation
        /// </summary>
        public Get()
        {
        }
        
        /// <summary>
        /// Project2 Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body)
        {
        }
        
        /// <summary>
        /// Project2 Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<Project2State,W3C.Soap.Fault> responsePort) : 
                base(body, responsePort)
        {
        }
    }
}
